# .github/workflows/deploy.yml
name: Deploy Vite app to GitHub Pages

on:
    push:
        branches: [gh-pages]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm ci

            - name: Create env file
              run: |
                  echo "VITE_HUGGING_FACE_TOKEN=${{ secrets.HUGGING_FACE_TOKEN }}" > .env

            - name: Build
              run: npm run build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist # Use the correct build output folder
                  branch: gh-pages # The branch to deploy to
